schema_version: 1

context:
  version: 3.3.0
  python_min: '3.11'

package:
  name: graphrag-chunking
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/graphrag-chunking/graphrag_chunking-${{ version }}.tar.gz
  sha256: 56d3fcfc4cbdfbb8caf86d03c3f2d6365a316fdf125137f3e0c4b9b35f4774ca

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling >=1.27.0,<2.0.0
    - pip
  run:
    - python >=${{ python_min }},<3.14
    - graphrag-common ==3.3.0
    - pydantic >=2.13,<3.dev0
tests:
  - python:
      imports:
        - graphrag_chunking
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - '*'

about:
  summary: Chunking utilities for GraphRAG
  license: MIT
  license_file: LICENSE
  homepage: https://pypi.org/project/graphrag-chunking/
  repository: https://github.com/microsoft/graphrag

extra:
  recipe-maintainers:
    - jan-janssen
